- name: prepare for dev tools
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
  - git
  - monit
  - build-essential
  - libssl-dev
  - libyaml-dev
  - libreadline6-dev
  - zlib1g-dev
  - libncurses5-dev
  - libffi-dev
  - libgdbm3
  - libgdbm-dev
  - libmysqld-dev
  - mysql-client
